# choose which image to use
FROM node:7.7.1

# Create app directory
WORKDIR /usr/src/app

# In dev we just mount the local directory 
# and run the server from there

CMD [ "node", "server/server.js"]
